---
ID: "907f47a9-83d8-4005-813a-2d8dad1852f3"
Parent: "d990e3f1-9cfd-46c8-9824-d6309d0e51a9"
Template: "d990e3f1-9cfd-46c8-9824-d6309d0e51a9"
Path: /sitecore/templates/Project/molina/PatientInfo/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BDBA83F0-14B4-5150-9922-3A015EE0BEC3}">
        <r
          id="{416C9D5A-DAA7-45CE-8F0A-37079FA8DBF2}"
          ph="jss-main"
          uid="{2B1E4104-A9C3-4124-ACE2-5F208A709706}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220228T032203Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
